spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/wrm"
    username: "postgres"
    password: "@@root@"
    driver-class-name: org.postgresql.Driver

app:
  default:
    algorithm: FIFO