spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/wrm"
    username: "postgres"
    password: "@@root@"
    driver-class-name: org.postgresql.Driver
  web:
    resources:
      add-mappings: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  default:
    algorithm: FIFO